### ISSUE TITLE
10장: 객체 리터럴

### ISSUE THREAD

**Issue by 1ilsang** [Road-of-CODEr/we-hate-js#37]
정리하기

**Comment by hayoung0Lee** [comment]
* 객체 리터럴 표기법: 사람이 이해할 수 있는 문자 또는 약속된 기호를 사용하여 값을 생성하는 표기법, 객체를 생성하기위한 표기법이다. 
* 객채는 0개 이상의 프로퍼티로 구성된 집합으로 프로퍼티 키와 값으로 구성된다. 
     * 프로퍼티의 값: JavaScript의 모든 값을 쓸수 있는데, 함수도 사용한다. 이경우를 메소드라고 부른다.  
     * 프로퍼티의 키: 빈문자열을 포함하는 모든 문자열 또는 심벌 값
* ES6에서 메서드를 정의할때 function 키워드를 생략한 축약 표현이 사용가능하다. 
```javascript
// ES5 
let obj = {
     name: 'Lee', 
     sayHi: function() {
          console.log("HI!!!" + this.name);
     }
}

obj.sayHi();


// ES6 
let obj = {
     name: 'Lee', 
     sayHi() {
          console.log("HI!!!" + this.name);
     }
}

obj.sayHi();
```

**Comment by soobing** [comment]
# Chap10. 객체 리터럴
JS는 객체(Object) 기반의 프로그래밍 언어. 객체가 무엇인지, 객체를 생성하는 방법중에 객체리터럴에 대해 알아본다. 그리고 객체 프로퍼티에 대해 좀 더 자세히 알아보자.
# 객체란?
- JS 에서 원시 값을 제외한 나머지 값(함수, 배열, 정규 표현식)은 모두 객체
- 객체 타입(object/reference type)은 다양한 타입의 값(원시 값 혹은 다른 객체)을 **하나의 단위로 구성**한 복합적인 `자료구조(data structure)`다.
  - 함수를 프로퍼티 값으로 사용 가능. 자바스크립트 함수는 일급객체라서 값으로 취급 가능. (= 메서드, 일반 함수와 구분하기 위해 프로퍼티 값이 함수인 경우 `메서드`라고 부름)
  - 원시 값은 변경 불가능(immutable)한 값이지만, 객체는 변경 가능(mutable)한 값
- 객체는 프로퍼티와 메서드로 구성된 집합체. 상태와 동작을 하나의 단위로 구조화 가능.
  - 프로퍼티: 객체의 상태를 나타내는 값(data)
  - 메서드: 프로퍼티(상태 데이터)를 참조하고 조작할 수 있는 동작(behavior)

# 객체 생성하는 방법

- JS는 프로토타입 기반 객체지향 언어라 다양한 객체 생성 방법을 지원
- [참고] 클래스 기반 객체지향 언어(C++, JAVA)는 클래스를 사전에 정의하고 필요한 시점에 new 연산자와 함께 생성자를 호출하여 인스턴스를 생성
  > 인스턴스?
  > 클래스에 의해 생성되어 **메모리에 저장된 실체**. 클레스는 인스턴스를 생성하기 위한 템플릿의 역할을 함.

```
- 객체 리터럴
- Object 생성자 함수
- Object.create 메서드
- 생성자 함수
- 클래스(ES6)
```

## 객체 리터럴
- 객체 리터럴은 객체를 생성하기 위한 표기법
- ({...}) 중괄호 내에 0개 이상의 프로퍼티 정의하여 객체 생성
> 객체 리터럴의 중괄호 vs 코드 블럭의 중괄호
> - 객체 리터럴은 값으로 평기되는 표현식. 그러므로 객체 리터럴의 닫는 중괄호 뒤에는 세미콜론을 붙임.
> - 코드 블럭의 닫는 중괄호 뒤에는 세미콜론을 붙이지 않음.

## 프로퍼티
- 객체는 프로퍼티의 집합
- 프로퍼티는 `키, 값`으로 구성
  - 빈문자열을 포함하는 모든 `문자열` 또는 `심벌 값`.
  - 프로퍼티 값: 자바스크립트에서 사용할 수 있는 모든 값

###  프로퍼티 키
- 빈문자열을 포함하는 모든 `문자열` 또는 `심벌 값`.
- 문자열이나 심벌값 외의 값을 사용하면 암묵적 타입 변환을 통해 문자열이 됨 (ex 숫자)
  ```js
  var foo = {
    0: 1,
    1: 2,
    2: 3
  }
  // 따옴표는 붙지 않지만 내부적으로는 숫자 키들이 문자열로 변환됨
  console.log(foo); // {0: 1, 1: 2, 2: 3}
  ```
- 프로퍼티 키는 식별자 역할을 함.
- 단, 식별자 규칙을 따를 필요는 없음.
- 식별자 네이밍 규칙을 따르지 않는 이름에는 반드시 따옴표를 사용해야함.
```
식별자 네이밍 규칙
- 식별자는 특수문자를 제외한 문자, 숫자, 언더스코어(_), 달러 기호($)를 포함할 수 있다.
- 단, 식별자는 특수문자를 제외한 문자, 언더스코어(_), 달러 기호($)로 시작해야 한다. 숫자로 시작하는 것은 허용하지 않는다.
- 예약어는 식별자로 사용할 수 없다.
(예약어는 프로그래밍 언어에서 사용되거 있거나 사용될 예정인 단어를 말함. ex. let, const, var, typeof 등등)
```
- 빈 문자열을 프로퍼티 키로 사용해도 에러가 발생하지 않지만, 키로서 의미를 갖지 못하므로 권장하지 않음.
- var, function과 같은 예약어를 키로 사용해도 에러가 발생하지 않으나 권장하지 않음.


### 프로퍼티 접근
- 프로퍼티 접근은 `마침표`, `대괄호`를 통해 접근 가능.
- 프로퍼티 키가 식별자 네이밍 규칙을 준수 하였다면, `마침표`, `대괄호` 표기법 모두 사용 가능.
```js
var person = {
  name: 'Lee'
};

// 1. 마침표 표기법으로 접근
console.log(person.name); // Lee
// 2. 대괄호 표기법으로 접근
// - 빈드시, 따옴표로 감싼 문자열로 프로퍼티 키를 접근해야함
// - 프로퍼티 키가 숫자로 이뤄진 문자열이면, 따옴표 생략 가능
console.log(person['name']); // Lee
```
- 객체에 존재하지 않는 프로퍼티 접근시 `undefined` 반환(ReferenceError 발생 X)

[퀴즈]
* 아래와 같이 접근시, 브라우저 환경과 Node.js에서 뱉는 에러가 다름. 어떻게 다른지, 그 이유는?
```js
var person = {
  'last-name': 'Lee',
  1: 10  
}
// 
person.last-name; 
```
* 정답
  - 브라우저: NaN (브라우저에는 name이라는 전역변수 존재)
  - Node.js: ReferenceError: name is not defined

### 프로퍼티 갱신/동적 생성/삭제
- 이미 존재하는 프로퍼티에 값 할당시, 프로퍼티 값이 갱신됨
- 존재하지 않는 프로퍼티에 값을 할당하면 프로퍼티가 동적으로 생성되어 추가되고 값이 할당됨
- `delete 연산자를 이용하여 프로퍼티 삭제 가능
  - 존재하지 않는 프로퍼티 삭제시 아무런 에러 없이 무시됨
  ```js
  var person = {
    name: 'Lee'
  }
  person.name = 'Sue'; // 갱신
  person.age = 20; // 동적 생성
  delete person.age; // 삭제
  ```
### 프로퍼티 축약
- ES6 에서는 변수 이름과 프로퍼티 키가 동일한 경우, 프로퍼티 키 생략 가능
```js
var x = 1, y = 2;
// ES5
var obj = {
  x: x,
  y: y
}
// ES6
var obj2 { x, y };
```

### 프로퍼티 계산
- ES6에서 계산된 프로퍼티 이름으로 키를 동적 생성하려면 대괄호 표기법([])을 사용해야 함.
```js
var obj = {};
var prefix = 'prop';
var i = 0;
// ES5
obj[prefix + '-' + ++i] = i;
// ES6
obj[`${prefix}-${++i}`] = i;
```

### 프로퍼티 메서드 축약 표현 ✨
- ES6에서 `메서드 축약 표현` 추가
- 축약표현으로 정의한 메서드는 프로퍼티에 할당한 함수와 다르게 동작함.
  - ES6에서 메서드는 `축약 표현으로 정의한 메서드` 만을 의미
  - non-constructor. 즉, 인스턴스 생성불가. 생성자 함수로서 호출이 불가능 하단 소리. (new 키워드 사용 불가)
  - prototype 프로퍼티를 가지고 있지 않음.
```js
// ES5
var obj = {
  name: 'Lee',
  sayHi: function() {
    console.log('Hi' + this.name);
  }
}

// ES6
var obj2 = {
  name: 'Lee',
  // 메서드 축약 표현
  sayHi() {
    console.log('Hi' + this.name);
  }
}
console.log(obj.sayHi())
```
