### ISSUE TITLE
우리들의 첫 밋업

### ISSUE THREAD

**Issue by soobing** [Road-of-CODEr/we-hate-js#60]
# 논의 해보고 싶은 것

- eslint로 프로젝트 한정하는거 괜찮은지
- 컨트리뷰션 경험
- eslint에서도 여러 기여방법이 있는데 어떤것에 관심이 있는지
    - parser
    - bug fix
    - rule 추가
- 어떻게 하면 계속 같이하는 느낌을 주고 받을 수 있을까?

**Comment by 1ilsang** [comment]
20210721

수박님의 하드캐리. 기초적인 기여 방법 설명회

다음 모임(26일)까지 레포 찍먹해보기 #62 

cc. @KimSejune @alledy
